spring:
  application:
    name: meCash App

  datasource:
    url: jdbc:mysql://localhost:3306/bank_app?createDatabaseIfNotExist=true
    username: root
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true
#  sql:
#    init:
#      mode: always



  mail:
    host: smtp.gmail.com
    port: 465
    username: possibleolayode5344@gmail.com
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs


jwt:
  secret: ${jwt_secret}
  ttl: 3600000


path:
  logging: C:\\Logs\\meCash\\


